name: "foliage"
description: "Generates a static HTML site"
inputs:
  source:
    description: "Directory of source"
    required: true
    default: "."
  target:
    description: "Directory of generated files"
    required: true
    default: "generated"
runs:
  using: "docker"
  image: "Dockerfile"
  args: 
    - publish --source ${{inputs.source}} --target ${{inputs.target}} ${{inputs.source}}/.foliage.ston
